import type { Metadata } from "next";
import GlobalDataProvider from "@/components/GlobalDataProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { SideBarOption } from "@/types/globalAppTypes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Autopilot Finance",
  // description: "Generated by create next app",
};

const getSideBarData = () => {
    const availableAutopilots: SideBarOption[] = [
      { asset: 'USDC', protocol: "morpho",  apy: 8.75, icon: "/coins/usdc.png", enabled: true }, // Morpho USDC Autopilot APY
      { asset: 'ETH', protocol: "morpho", apy: 4.38, icon: "/coins/eth.png" },   // Morpho ETH Autopilot APY
      { asset: 'cbBTC', protocol: "morpho", apy: 2.19, icon: "/coins/cbBTC.png" }, // Morpho cbBTC Autopilot APY
      { asset: 'USDC', protocol: "euler", apy: 7.35, icon: "/coins/usdc.png" }, // Euler USDC Autopilot APY
      { asset: 'ETH', protocol: "euler", apy: 3.73, icon: "/coins/eth.png" },   // Euler ETH Autopilot APY
      { asset: 'cbBTC', protocol: "euler", apy: 1.86, icon: "/coins/cbBTC.png" }, // Euler cbBTC Autopilot APY
    ];
    return availableAutopilots;
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const availableAutopilots = getSideBarData();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-gray-50 flex">
          <GlobalDataProvider availableAutopilots={availableAutopilots}>
            <Sidebar
              sideBarData={availableAutopilots}
            />
            {children}
          </GlobalDataProvider>
        </div>
      </body>
    </html>
  );
}
