import { ProjectsData } from '@/types/globalAppTypes';

//mock data for projects
export const vaultsData: ProjectsData = {
  'morpho-USDC': {
    name: 'Morpho',
    asset: 'USDC',
    icon: '/projects/morpho.png',
    assetIcon: '/coins/usdc.png',
    currentAPY: 0.0875,
    secondBestAPY: 0.085,
    currentEarnings: 9309,
    autopilotBalance: 206915.0,
    walletBalance: 10000.0,
    monthlyForecast: 1509,
    weeklyApy: 8.75,
    monthlyApy: 8.75,
    quateryApy: 8.42,
    tvl: '$10.8M',
    allocations: [
      { name: 'Gauntlet USDC Core', apy: 7.52, amount: 77593, allocation: 43 },
      { name: 'Re7 USDC', apy: 7.51, amount: 62075, allocation: 34.0 },
      { name: 'Moonwell USDC', apy: 6.53, amount: 46559, allocation: 23 },
    ],
    recentEarnings: [
      { time: '2 hr', amount: 22.35, type: 'yield' },
      { time: '3 hr', amount: 18.92, type: 'yield' },
      { time: '5 hr', amount: 15.67, type: 'yield' },
      { time: '6 hr', amount: 19.82, type: 'yield' },
      { time: '8 hr', amount: 25.14, type: 'yield' },
    ],
    benchmarkData: [
      { name: 'Autopilot', description: 'Smart Yield Router', apy: 8.75, isAutopilot: true },
      { name: 'Extrafi XLend USDC Vault (Gauntlet)', description: 'Morpho Vault', apy: 8.5 },
      { name: 'Ionic Ecosystem', description: 'Morpho Vault', apy: 8.5 },
      { name: 'Moonwell Flagship', description: 'Morpho Vault', apy: 7.94 },
      { name: 'Seamless', description: 'Morpho Vault', apy: 7.88 },
      { name: 'Smokehouse', description: 'Morpho Vault', apy: 7.82 },
      { name: 'Apostro Resolv', description: 'Morpho Vault', apy: 7.76 },
      { name: 'Clearstar OpenEden', description: 'Morpho Vault', apy: 7.43 },
      { name: 'Steakhouse', description: 'Morpho Vault', apy: 7.24 },
      { name: 'Gauntlet Prime', description: 'Morpho Vault', apy: 7.19 },
      { name: 'Gauntlet Core', description: 'Morpho Vault', apy: 6.95 },
      { name: 'Spark', description: 'Morpho Vault', apy: 5.67 },
      { name: 'Pyth USDC (Re7 Labs)', description: 'Morpho Vault', apy: 4.93 },
      { name: 'Re7 Labs', description: 'Morpho Vault', apy: 4.78 },
      { name: 'Universal USDC (Re7 Labs)', description: 'Morpho Vault', apy: 3.55 },
    ],
    yieldSources: [
      { name: 'High Yield Clearstar USDC', address: '0xa1b2...c3d4' },
      { name: 'Extrafi XLend USDC', address: '0xe5f6...7890' },
      { name: 'Clearstar Reactor OpenEden Boosted USDC', address: '0x1234...abcd' },
      { name: 'Universal USDC', address: '0x5678...efgh' },
      { name: 'Steakhouse Prime USDC', address: '0x9abc...ijkl' },
      { name: 'Gauntlet USDC Frontier', address: '0xdef0...mnop' },
      { name: 'Steakhouse High Yield USDC v1.1', address: '0x2345...qrst' },
      { name: 'Apostro Resolv USDC', address: '0x6789...uvwx' },
      { name: 'Seamless USDC Vault', address: '0xabcd...yz12' },
      { name: 'Gauntlet USDC Prime', address: '0xef34...5678' },
      { name: 'Moonwell Flagship USDC', address: '0x90ab...cdef' },
      { name: 'Yearn OG USDC', address: '0x1234...5678' },
      { name: 'Gauntlet USDC Core', address: '0x90ab...cdef' },
      { name: 'Smokehouse USDC', address: '0xfedc...ba98' },
      { name: 'Ionic Ecosystem USDC', address: '0x7654...3210' },
      { name: 'Steakhouse High Yield USDC', address: '0xba98...7654' },
      { name: 'Steakhouse USDC', address: '0x3210...fedc' },
      { name: 'Re7 USDC', address: '0x8765...4321' },
      { name: 'Spark USDC Vault', address: '0xcdef...0123' },
      { name: 'Pyth USDC', address: '0x4567...89ab' },
    ],
  },
  'morpho-ETH': {
    name: 'Morpho',
    asset: 'ETH',
    icon: '/projects/morpho.png',
    assetIcon: '/coins/eth.png',
    currentAPY: 0.0438,
    secondBestAPY: 0.0425,
    currentEarnings: 12.45,
    autopilotBalance: 85.67,
    walletBalance: 2.5,
    monthlyForecast: (85.67 * 0.0438) / 12,
    weeklyApy: 4.38,
    monthlyApy: 4.21,
    quateryApy: 8.42,
    tvl: '$10.8M',
    allocations: [
      { name: 'Gauntlet ETH Core', apy: 4.68, amount: 32.25, allocation: 42 },
      { name: 'Gauntlet ETH Prime', apy: 4.51, amount: 25.7, allocation: 35 },
      { name: 'Re7 ETH', apy: 4.32, amount: 18.84, allocation: 23 },
    ],
    recentEarnings: [
      { time: '3 min', amount: 0.0024, type: 'yield' },
      { time: '52 min', amount: 0.0035, type: 'yield' },
      { time: '1hr', amount: 0.0028, type: 'yield' },
      { time: '2hr', amount: 0.0041, type: 'yield' },
      { time: '4hr', amount: 0.0033, type: 'yield' },
    ],
    benchmarkData: [
      { name: 'Autopilot', description: 'Smart Yield Router', apy: 4.38, isAutopilot: true },
      { name: 'Extrafi XLend ETH Vault (Gauntlet)', description: 'Morpho Vault', apy: 4.25 },
      { name: 'Ionic Ecosystem ETH', description: 'Morpho Vault', apy: 4.25 },
      { name: 'Moonwell Flagship ETH', description: 'Morpho Vault', apy: 3.97 },
      { name: 'Seamless ETH', description: 'Morpho Vault', apy: 3.94 },
      { name: 'Smokehouse ETH', description: 'Morpho Vault', apy: 3.91 },
      { name: 'Apostro Resolv ETH', description: 'Morpho Vault', apy: 3.88 },
      { name: 'Clearstar OpenEden ETH', description: 'Morpho Vault', apy: 3.72 },
      { name: 'Steakhouse ETH', description: 'Morpho Vault', apy: 3.62 },
      { name: 'Gauntlet Prime ETH', description: 'Morpho Vault', apy: 3.6 },
      { name: 'Gauntlet Core ETH', description: 'Morpho Vault', apy: 3.48 },
      { name: 'Spark ETH', description: 'Morpho Vault', apy: 2.84 },
      { name: 'Pyth ETH (Re7 Labs)', description: 'Morpho Vault', apy: 2.47 },
      { name: 'Re7 Labs ETH', description: 'Morpho Vault', apy: 2.39 },
      { name: 'Universal ETH (Re7 Labs)', description: 'Morpho Vault', apy: 1.78 },
    ],
    yieldSources: [],
  },
  'morpho-cbBTC': {
    name: 'Morpho',
    asset: 'cbBTC',
    icon: '/projects/morpho.png',
    assetIcon: '/coins/cbBTC.png',
    currentAPY: 0.0219,
    secondBestAPY: 0.0213,
    currentEarnings: 0.89,
    autopilotBalance: 3.24,
    walletBalance: 0.15,
    monthlyForecast: (3.24 * 0.0219) / 12,
    weeklyApy: 2.19,
    monthlyApy: 2.1,
    quateryApy: 8.42,
    tvl: '$10.8M',
    allocations: [
      { name: 'Re7 cbBTC', apy: 3.9, amount: 1.22, allocation: 45 },
      { name: 'Gauntlet BTC Core', apy: 3.76, amount: 0.97, allocation: 32 },
      { name: 'Smokehouse cbBTC', apy: 3.61, amount: 0.71, allocation: 23 },
    ],
    recentEarnings: [
      { time: '5 min', amount: 0.000089, type: 'yield' },
      { time: '38 min', amount: 0.000134, type: 'yield' },
      { time: '1hr', amount: 0.000096, type: 'yield' },
      { time: '3hr', amount: 0.000156, type: 'yield' },
      { time: '5hr', amount: 0.000112, type: 'yield' },
    ],
    benchmarkData: [
      { name: 'Autopilot', description: 'Smart Yield Router', apy: 2.19, isAutopilot: true },
      { name: 'Extrafi XLend cbBTC Vault (Gauntlet)', description: 'Morpho Vault', apy: 2.13 },
      { name: 'Ionic Ecosystem cbBTC', description: 'Morpho Vault', apy: 2.13 },
      { name: 'Moonwell Flagship cbBTC', description: 'Morpho Vault', apy: 1.99 },
      { name: 'Seamless cbBTC', description: 'Morpho Vault', apy: 1.97 },
      { name: 'Smokehouse cbBTC', description: 'Morpho Vault', apy: 1.96 },
      { name: 'Apostro Resolv cbBTC', description: 'Morpho Vault', apy: 1.94 },
      { name: 'Clearstar OpenEden cbBTC', description: 'Morpho Vault', apy: 1.86 },
      { name: 'Steakhouse cbBTC', description: 'Morpho Vault', apy: 1.81 },
      { name: 'Gauntlet Prime cbBTC', description: 'Morpho Vault', apy: 1.8 },
      { name: 'Gauntlet Core cbBTC', description: 'Morpho Vault', apy: 1.74 },
      { name: 'Spark cbBTC', description: 'Morpho Vault', apy: 1.42 },
      { name: 'Pyth cbBTC (Re7 Labs)', description: 'Morpho Vault', apy: 1.23 },
      { name: 'Re7 Labs cbBTC', description: 'Morpho Vault', apy: 1.2 },
      { name: 'Universal cbBTC (Re7 Labs)', description: 'Morpho Vault', apy: 0.89 },
    ],
    yieldSources: [],
  },
  'euler-USDC': {
    name: 'Euler',
    asset: 'USDC',
    icon: '/projects/euler.png',
    assetIcon: '/coins/usdc.png',
    currentAPY: 0.0735,
    secondBestAPY: 0.0725,
    currentEarnings: 38674.25,
    autopilotBalance: 180250.0,
    walletBalance: 10000.0,
    monthlyForecast: (180250 * 0.0735) / 12,
    weeklyApy: 7.35,
    monthlyApy: 7.12,
    quateryApy: 8.42,
    tvl: '$10.8M',
    allocations: [],
    recentEarnings: [
      { time: '5 min', amount: 7.89, type: 'yield' },
      { time: '35 min', amount: 14.23, type: 'yield' },
      { time: '1hr', amount: 11.67, type: 'yield' },
      { time: '2hr', amount: 18.45, type: 'yield' },
      { time: '4hr', amount: 22.1, type: 'yield' },
    ],
    benchmarkData: [
      { name: 'Autopilot', description: 'Smart Yield Router', apy: 7.35, isAutopilot: true },
      { name: 'Euler Core USDC', description: 'Euler Vault', apy: 7.25 },
      { name: 'Euler Prime USDC', description: 'Euler Vault', apy: 6.98 },
      { name: 'Euler Growth USDC', description: 'Euler Vault', apy: 6.67 },
      { name: 'Euler Max USDC', description: 'Euler Vault', apy: 6.45 },
      { name: 'Euler Base USDC', description: 'Euler Vault', apy: 6.12 },
      { name: 'Euler Safe USDC', description: 'Euler Vault', apy: 5.89 },
      { name: 'Euler Balance USDC', description: 'Euler Vault', apy: 5.76 },
      { name: 'Euler Basic USDC', description: 'Euler Vault', apy: 5.45 },
      { name: 'Euler Stable USDC', description: 'Euler Vault', apy: 5.34 },
      { name: 'Euler Reserve USDC', description: 'Euler Vault', apy: 4.98 },
      { name: 'Euler Conservative USDC', description: 'Euler Vault', apy: 4.23 },
    ],
    yieldSources: [],
  },
  'euler-ETH': {
    name: 'Euler',
    asset: 'ETH',
    icon: '/projects/euler.png',
    assetIcon: '/coins/eth.png',
    currentAPY: 0.0373,
    secondBestAPY: 0.0363,
    currentEarnings: 10.89,
    autopilotBalance: 76.23,
    walletBalance: 2.5,
    monthlyForecast: (76.23 * 0.0373) / 12,
    weeklyApy: 3.73,
    monthlyApy: 3.56,
    quateryApy: 8.42,
    tvl: '$10.8M',
    allocations: [],
    recentEarnings: [
      { time: '4 min', amount: 0.0022, type: 'yield' },
      { time: '41 min', amount: 0.0031, type: 'yield' },
      { time: '1hr', amount: 0.0026, type: 'yield' },
      { time: '3hr', amount: 0.0038, type: 'yield' },
      { time: '5hr', amount: 0.0029, type: 'yield' },
    ],
    benchmarkData: [
      { name: 'Autopilot', description: 'Smart Yield Router', apy: 3.73, isAutopilot: true },
      { name: 'Euler Core ETH', description: 'Euler Vault', apy: 3.63 },
      { name: 'Euler Prime ETH', description: 'Euler Vault', apy: 3.49 },
      { name: 'Euler Growth ETH', description: 'Euler Vault', apy: 3.34 },
      { name: 'Euler Max ETH', description: 'Euler Vault', apy: 3.23 },
      { name: 'Euler Base ETH', description: 'Euler Vault', apy: 3.06 },
      { name: 'Euler Safe ETH', description: 'Euler Vault', apy: 2.95 },
      { name: 'Euler Balance ETH', description: 'Euler Vault', apy: 2.88 },
      { name: 'Euler Basic ETH', description: 'Euler Vault', apy: 2.73 },
      { name: 'Euler Stable ETH', description: 'Euler Vault', apy: 2.67 },
      { name: 'Euler Reserve ETH', description: 'Euler Vault', apy: 2.49 },
      { name: 'Euler Conservative ETH', description: 'Euler Vault', apy: 2.12 },
    ],
    yieldSources: [],
  },
  'euler-cbBTC': {
    name: 'Euler',
    asset: 'cbBTC',
    icon: '/projects/euler.png',
    assetIcon: '/coins/cbBTC.png',
    currentAPY: 0.0186,
    secondBestAPY: 0.0181,
    currentEarnings: 0.67,
    autopilotBalance: 2.89,
    walletBalance: 0.15,
    monthlyForecast: (2.89 * 0.0186) / 12,
    weeklyApy: 1.86,
    monthlyApy: 1.78,
    quateryApy: 8.42,
    tvl: '$10.8M',
    allocations: [],
    recentEarnings: [
      { time: '7 min', amount: 0.000067, type: 'yield' },
      { time: '44 min', amount: 0.000098, type: 'yield' },
      { time: '1hr', amount: 0.000074, type: 'yield' },
      { time: '3hr', amount: 0.000121, type: 'yield' },
      { time: '5hr', amount: 0.000085, type: 'yield' },
    ],
    benchmarkData: [
      { name: 'Autopilot', description: 'Smart Yield Router', apy: 1.86, isAutopilot: true },
      { name: 'Euler Core cbBTC', description: 'Euler Vault', apy: 1.81 },
      { name: 'Euler Prime cbBTC', description: 'Euler Vault', apy: 1.75 },
      { name: 'Euler Growth cbBTC', description: 'Euler Vault', apy: 1.67 },
      { name: 'Euler Max cbBTC', description: 'Euler Vault', apy: 1.61 },
      { name: 'Euler Base cbBTC', description: 'Euler Vault', apy: 1.53 },
      { name: 'Euler Safe cbBTC', description: 'Euler Vault', apy: 1.47 },
      { name: 'Euler Balance cbBTC', description: 'Euler Vault', apy: 1.44 },
      { name: 'Euler Basic cbBTC', description: 'Euler Vault', apy: 1.36 },
      { name: 'Euler Stable cbBTC', description: 'Euler Vault', apy: 1.34 },
      { name: 'Euler Reserve cbBTC', description: 'Euler Vault', apy: 1.25 },
      { name: 'Euler Conservative cbBTC', description: 'Euler Vault', apy: 1.06 },
    ],
    yieldSources: [],
  },
};
